<a href="https://colab.research.google.com/github/kevinsen-git/TF_Basics/blob/main/00_Intro_to_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Demonstrate some basics in Tensor Flow
* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up regular pyton function)
* Using GPUs (or TPUs) with Tensor Flow
* A few excercises to try yourself 



## Introduction to Tensors 

In [79]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# Create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=70>

In [ ]:
#Check the number of dimesions of a tensor
scalar.ndim


0

In [ ]:
#Create a vector 
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check dimensions of vector
vector.ndim

1

In [ ]:
#Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#Check dimensions of matrix
matrix.ndim

2

In [ ]:
#create a 3d tensor 
tensor_3 = tf.constant([
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ]
                       ],dtype=tf.float32)
tensor_3.ndim

3

In [ ]:
tensor_3

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]]], dtype=float32)>

In [ ]:
#create a 3d tensor 
tensor_3 = tf.constant([
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ]                        
                       ],dtype=tf.float32)
tensor_3

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]]], dtype=float32)>

In [ ]:
# Create a 4d tensor 
tensor_4 = tf.constant(
                       [ 
                       [
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ,
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ],
                       [
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ,
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ]
                       ]     
                      )
tensor_4


<tf.Tensor: shape=(2, 4, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]], dtype=int32)>

In [ ]:
# Create a 0,1,2,3,4,5 dimensioanl tensors
tensor_0 = tf.constant(0)
tensor_1 = tf.constant([0])
tensor_2 = tf.constant([[0]])
tensor_3 = tf.constant([[[0]]])
tensor_4 = tf.constant([[[[0]]]])
tensor_5 = tf.constant([[[[[0]]]]])


tensor_0,tensor_1,tensor_2,tensor_3,tensor_4,tensor_5 

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>,
 <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[0]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[0]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1, 1), dtype=int32, numpy=array([[[[0]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=int32, numpy=array([[[[[0]]]]], dtype=int32)>)

### Creating tensors with tf.variable

New notation Variables 1st letter caps, constants first letter lower case 
tf.constant, tf.Variable 


In [ ]:
tf.Variable


tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor 


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
changeable_tensor[1].assign(100)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 10, 100], dtype=int32)>

In [ ]:
unchangeable_tensor[1].assign(-1)

AttributeError: ignored

In [ ]:
chngble_tensor=tf.Variable([[10],[5]])
chngble_tensor

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[10],
       [ 5]], dtype=int32)>

In [ ]:
chngble_tensor[1].assign([6])
chngble_tensor

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[6],
       [6]], dtype=int32)>

In [2]:
# How to change elements in a multi dimensional tensor ?
chngble_tensor=tf.Variable([[1,2],[3,4]])
chngble_tensor[0,2:2]


<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [19]:
# Can pick elements using .numpy 
# Works fine but cannot use assign to change its value 
chngble_tensor=tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]])
x1=chngble_tensor.numpy()[0][1][1]
x1



4

In [41]:
# Extracting parts of a tensor 
# Negative indexing to extract from end
# Going forward start at 0 
# Going backwards starts at -1 ! 
# And a direct assign works !!
x = tf.Variable([[[1., 2.], [3., 4. ], [5. , 6. ]],
                 [[7., 8.], [9., 10.], [11., 12.]]])
x[0, 2, 1].assign(100)
x[1, 1, -2].assign(200)

x,x[0, 2, 1], x[1,1,-2]

(<tf.Variable 'Variable:0' shape=(2, 3, 2) dtype=float32, numpy=
 array([[[  1.,   2.],
         [  3.,   4.],
         [  5., 100.]],
 
        [[  7.,   8.],
         [200.,  10.],
         [ 11.,  12.]]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=100.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=200.0>)

In [53]:
# Can assign a whole chunk of stuff !!!! not just an individual element 
x = tf.Variable([[[1., 2.], [3., 4. ], [5. , 6. ]],
                 [[7., 8.], [9., 10.], [11., 12.]]])

x[0,1].assign([300,400])
x,x[0,0]

(<tf.Variable 'Variable:0' shape=(2, 3, 2) dtype=float32, numpy=
 array([[[  1.,   2.],
         [300., 400.],
         [  5.,   6.]],
 
        [[  7.,   8.],
         [  9.,  10.],
         [ 11.,  12.]]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>)

In [77]:
# Extracting parts of a tensor 
# https://sodocumentation.net/tensorflow/topic/2511/tensor-indexing
# Use the indexing operator (based on tf. slice() ) to extract a contiguous slice from the tensor. ...
# Use the tf. gather() op to select a non-contiguous slice from the tensor.
# x has shape [2, 3, 2]
# Negative indexing to extract from end 
# The 2nd part of the slice gives you the final shape !!
x = tf.constant([[[1., 2.], [3., 4. ], [5. , 6. ]],
                 [[7., 8.], [9., 10.], [11., 12.]]])

# Extracts x[0, 1:2, :] == [[[ 3.,  4.]]]
res1 = tf.slice(x, [0, 1, 0], [1, 1, -1])
res2 = tf.slice(x, [0, 1, 0], [1, 1, 2])
res3 = tf.slice(x, [0, 1, 0], [2, 1, 2])
res4 = tf.slice(x, [0, 1, 1], [1, -1, -1])

x,res1, res2, res3, res4

# The shape from slice is not the same as using an index 
# So what does slice do exactly ??
# Its a from , and the step sieze notation 
# NOT a from, to notation !
# [0,1,0],[1,1,-1] - means 
# Start at 0 ags get 1 slice  [[1., 2.], [3., 4. ], [5. , 6. ]]
# then start at 1 and get one slice of that = [3., 4. ]
# then get start at 0 and get all the slices of that = [3.,4.]
# Note the shapes ...they are still 3 dimensional !!! like the original one 

(<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
 array([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],
 
        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 2), dtype=float32, numpy=array([[[3., 4.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 2), dtype=float32, numpy=array([[[3., 4.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
 array([[[ 3.,  4.]],
 
        [[ 9., 10.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
 array([[[4.],
         [6.]]], dtype=float32)>)

In [81]:
# Using tf.gather 
import numpy as np
data = np.reshape(np.arange(30), [5, 6])
params = tf.constant(data)
indices = tf.constant([0, 3])
selected = tf.gather(params, indices)
params, indices, selected


(<tf.Tensor: shape=(5, 6), dtype=int64, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int64, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [18, 19, 20, 21, 22, 23]])>)

In [85]:
# Note that indices can have any shape, but the elements stored in indices always only refer to the first dimension of params. 
# E.g. if you want to retrieve both the 1st and 3rd row and the 2nd and 4th row at the same time, you can do this:

indices1 = tf.constant([[0, 2], [1, 3]])
indices2 = tf.constant([0,2,1,3])

selected1 = tf.gather(params, indices1)
selected2 = tf.gather(params, indices2)

selected1, selected2 

(<tf.Tensor: shape=(2, 2, 6), dtype=int64, numpy=
 array([[[ 0,  1,  2,  3,  4,  5],
         [12, 13, 14, 15, 16, 17]],
 
        [[ 6,  7,  8,  9, 10, 11],
         [18, 19, 20, 21, 22, 23]]])>,
 <tf.Tensor: shape=(4, 6), dtype=int64, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17],
        [ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])>)

In [116]:
# Generating a list 
y1=list(range(4, -3,-1))
y2=list(range(4,-1,-2))
y3=list(range(4,-1,-1))
y1,y2,y3


([4, 3, 2, 1, 0, -1, -2], [4, 2, 0], [4, 3, 2, 1, 0])

In [117]:
# How to reverse all rows
import numpy as np
x=np.reshape(np.arange(30),[5,6])
indices = tf.constant(list(range(4, -1, -1)))
selected = tf.gather(params, indices)
x,indices, selected

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>,
 <tf.Tensor: shape=(5, 6), dtype=int64, numpy=
 array([[24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23],
        [12, 13, 14, 15, 16, 17],
        [ 6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5]])>)

In [ ]:
#If you need access to any other than the first dimension, you could work around that using tf.transpose: E.g. to gather columns instead of rows in our example, you could do this:

indices = tf.constant([0, 2])
selected = tf.gather(tf.transpose(params, [1, 0]), indices)
selected_t = tf.transpose(selected, [1, 0]) 
#However, tf.transpose is rather expensive, so it might be better to use tf.gather_nd for this use case.

# ??????????????????