<a href="https://colab.research.google.com/github/kevinsen-git/TF_Basics/blob/main/00_Intro_to_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Demonstrate some basics in Tensor Flow
* Introduction to Tensors
* Getting information from Tensors
* Manipulating Tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up regular pyton function)
* Using GPUs (or TPUs) with Tensor Flow
* A few excercises to try yourself 



## Introduction to Tensors 

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# Create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=70>

In [ ]:
#Check the number of dimesions of a tensor
scalar.ndim


0

In [ ]:
#Create a vector 
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check dimensions of vector
vector.ndim

1

In [ ]:
#Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#Check dimensions of matrix
matrix.ndim

2

In [ ]:
#create a 3d tensor 
tensor_3 = tf.constant([
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ]
                       ],dtype=tf.float32)
tensor_3.ndim

3

In [ ]:
tensor_3

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]]], dtype=float32)>

In [ ]:
#create a 3d tensor 
tensor_3 = tf.constant([
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ],
                       [
                        [111,112,113],[121,122,123],
                        [211,212,213],[221,222,223]
                       ]                        
                       ],dtype=tf.float32)
tensor_3

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]],

       [[111., 112., 113.],
        [121., 122., 123.],
        [211., 212., 213.],
        [221., 222., 223.]]], dtype=float32)>

In [3]:
# Create a 4d tensor 
tensor_4 = tf.constant(
                       [ 
                       [
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ,
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ],
                       [
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ,
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]
                       ]
                       ]     
                      )
tensor_4


<tf.Tensor: shape=(2, 4, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]], dtype=int32)>

In [11]:
# Create a 0,1,2,3,4,5 dimensioanl tensors
tensor_0 = tf.constant(0)
tensor_1 = tf.constant([0])
tensor_2 = tf.constant([[0]])
tensor_3 = tf.constant([[[0]]])
tensor_4 = tf.constant([[[[0]]]])
tensor_5 = tf.constant([[[[[0]]]]])


tensor_0,tensor_1,tensor_2,tensor_3,tensor_4,tensor_5 

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>,
 <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[0]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[0]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1, 1), dtype=int32, numpy=array([[[[0]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=int32, numpy=array([[[[[0]]]]], dtype=int32)>)

### Creating tensors with tf.variable

New notation Variables 1st letter caps, constants first letter lower case 
tf.constant, tf.Variable 


In [14]:
tf.Variable


tensorflow.python.ops.variables.Variable